---

# - nxos_facts:
#     provider: "{{ provider }}"
#     gather_subset:
#       - config

- name: Get Hostname
  register: configured_hostname
  no_log: True
  nxos_command:
    provider: "{{ provider }}"
    commands: show run | include ^hostname
    # save: yes

# - name: Configured hostname
#   debug:
#     msg: "Configured hostname: {{ configured_hostname }}"

- name: "Fact: Configured Hostname"
  set_fact: configured_hostname="{{ configured_hostname.stdout | join('') | regex_replace('\\S+\\s+(\\S+)', '\\1') | replace('\n', '') }}"
  no_log: True


- name: hostname
  when: configured_hostname != inventory_hostname
  # when: ansible_net_hostname == inventory_hostname
  nxos_config:
    provider: "{{ provider }}"
    lines: hostname {{ inventory_hostname }}
    save: yes